<table>
    <thead>
        <tr>
            <th>Organization Name</th>
            <th>Twitter</th>
            <th>Contact</th>
            <th style="text-align: right;">
            <a href="<?=App::config('url')?>organization/new">Add New</a>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($entities as $red): ?>
            <tr>
                <td><?=$red->name?></td>
                <td><?=$red->twitter?></td>
                <td><?=$red->contact?></td>
                <td>
                    <a href="<?=App::config('url')?>organization/change?id=<?=$red->id?>">
                        <i title="change" class="fas fa-2x fa-pencil-alt"></i>
                    </a>
                    <?php if($red->organization==0): ?>
                        <a href="<?=App::config('url')?>organization/delete?id=<?=$red->id?>"
                        onclick="return confirm('Are you sure?');">
                        <i title="delete" style="color: red" class="fas fa-trash-alt"></i></a>
                    <?php endif;?>
                </td>
            </tr>

        <?php endforeach; ?>
    </tbody>
</table>