<form class="log-in-form"
    action="<?=App::config('url')?>index/authorization"
    method="POST">
    <h4 class="text-center">Authorization</h4>
    <label>Email
        <input type="email" name="email" values="<?=$email?>">
    </label>
    <label>Password 
        <input type="password" name="password">
    </label>
    <p><input type="submit" class="button expanded" value="LogIn"></input></p>
    <?=$message?>
    </form>

