<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
    <div class="title-bar-title">Menu</div>
</div>


<div class="top-bar" id="responsive-menu">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
        <li>
            <a href="<?App::config('url')?>">
                <?App::config('AppName')?>
            </a>
        </li>
        <li><a href="<?=App::config('url')?>index/era">ERA</a></li>
        <li><a href="<?=App::config('url')?>index/contact">Contact</a></li>
    </ul>
</div>
<div class="top-bar-right">
    <ul class="menu">
        <li>login/logout</li>
        </ul>
    </div>
</div>
