<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
    <div class="title-bar-title">Menu</div>
</div>


<div class="top-bar" id="responsive-menu">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
        <li>
            <a href="<?App::config('url')?>">
                <?App::config('AppName')?>
            </a>
        </li>

        <?php if(isset($_SESSION['authorized'])): ?>
        <ul class="vertical menu">
        <li><a href="<?=App::config('url')?>player/index">Players</a></li>
        <li><a href="<?=App::config('url')?>organization/index">Teams</a></li>
        <li><a href="<?=App::config('url')?>coach/index">Coaches</a></li>
        <?php if($_SESSION['authorized']->role=='admin'): ?>
            <li><a href="#">Operators</a></li> 
            <?php endif;?>       
        </ul>
       </li>
    <?php endif;?>

        <li><a href="<?=App::config('url')?>index/era">ERA</a></li>
        <li><a href="<?=App::config('url')?>index/contact">Contact</a></li>
    </ul>
</div>
<div class="top-bar-right">
    <ul class="menu">
        <li>
        <?php if(!isset($_SESSION['authorized'])): ?>
            <a href="<?App::config('url')?>index/login">Authorize</a>
            <?php else: ?>

            
                <a href="<?App::config('url')?>index/logout">
                  <?=$_SESSION['authorized']->name?> <?=$_SESSION['authorized']->surname?> Log Out
                
                </a>
            <?php endif;?>
        </li>
        </ul>
    </div>
</div>
