<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
    <div class="title-bar-title">Menu</div>
</div>


<div class="top-bar" id="responsive-menu">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text"><?=App::config('AppName')?></li>
        <li><a href="#0">Two</a></li>
        <li><a href="#0">Three</a></li>
    </ul>
</div>
<div class="top-bar-right">
    <ul class="menu">
        <li>login/logout</li>
        </ul>
    </div>
</div>
