<table>
    <thead>
        <tr>
            <th>Name & Surname</th>
            <th>Country</th>
            <th>Nickname</th>
            <th>Organization</th>
            <th style="text-align: right;">
            <a href="<?=App::config('url')?>Player/new">Add New</a>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($players as $red): ?>
            <tr>
                <td><?=$red->name?> <?=$red->surname?> </td>
                <td><?=$red->country?></td>
                <td><?=$red->nickname?></td>
                <td><?=$red->organization?></td>
                
                <td>
                    <a href="<?=App::config('url')?>player/change?id=<?=$red->id?>">
                        <i title="change" class="fas fa-2x fa-pencil-alt"></i>
                    </a>
                    <?php if($red->playerorg==0): ?>
                        <a href="<?=App::config('url')?>player/delete?id=<?=$red->id?>"
                        onclick="return confirm('Are you sure?');">
                        <i title="delete" style="color: red" class="fas fa-trash-alt"></i></a>
                    <?php endif;?>
                </td>
            </tr>

        <?php endforeach; ?>
    </tbody>
</table>