<form class="log-in-form"
    action="<?=App::config('url')?>coach/new"
    method="POST">

    <h4 class="text-center">Add a new coach</h4>
    <label>Name
        <input type="text"name="name" value="<?=$entity->name?>">   
    </label>

        
        
    <label>Surname
        <input type="text" name="surname" value="<?=$entity->surname?>">
    </label>

    <div class="grid-x grid-padding-x">
        <div class="cell-large-4"> 
    <label>Country
        <input type="text" name="country" value="<?=$entity->country?>">
    </label>
    </div>
    <div class="cell-large-4"> 
    <label>Nickname
        <input type="text" name="nickname" value="<?=$entity->nickname?>">
    </label>
    </div>
    <div class="cell-large-4"> 
    </div>  
</div>

    <?=$message?>

    <div class="grid-x grid-padding-x">
  <div class="cell small-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>coach/index">Back</a>
  </div>
  <div class="cell small-6 large-6">
    <input type="submit" class="button expanded" value="Submit"></input>
  </div>
</div>

</form>